---
title: Cyber Sith Academy
description: Learn and practice cybersecurity by playing with our VMs.
url: ""
baseurl: ""

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md', '/CONTRIBUTING.md']

permalink: pretty

collections:
  vms:
    output: true

defaults:
  - scope:
      path: '_vms'
    values:
      layout: bin
